catch {::common::set_param -quiet hls.xocc.mode csynth};
#
# Hls run script generated by the compiler
#

set xocc_optimize_level 0
open_project gathered_kernel
set_top gathered_kernel
add_files "/home/yzf/workspace/my_mgvf/gathered_compute_overlap/src/gathered_kernel.cpp"
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300MHz -name default
config_flow -target vitis
config_export -vivado_optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
config_export -format ip_catalog -ipname workload
csynth_design
close_project
puts "HLS completed successfully"
exit